spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8089

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# ??????????? (???????????)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-service-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
#spring.kafka.producer.properties.spring.json.type.mapping: order:com.example.orderservice.event.OrderEvent

#consumer:
#group-id: order-service-group
#key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#properties:
#spring.json.trusted.packages: "*"
#spring.json.type.mapping: order:com.example.orderservice.event.OrderEvent

